
openapi: 3.0.3
info:
  title: User Service API
  description: API for user authentication and profile management22
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: http://localhost:8080/v1
    description: Local development server

paths:
  /fetchcatalogV1:
    post:
      summary: Fetch Product catalog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CatalogRequest'
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CatalogResponse'
  /fetchcatalog2V2:
    post:
      summary: Fetch Product catalog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CatalogRequest'
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CatalogResponse'

components:
  schemas:
    CatalogRequest:
      type: object
      properties:
        currentPage:
          type: integer
    CatalogResponse:
      type: array
      properties:
        id:
          type: integer
        imageUrl:
          type: string
        title:
          type: string
        description:
          type: string
        inStock:
          type: string
        rating:
          type: number
        price:
          type: number
        currency:
          type: string
